var onePieceData = [
  {
    id: 1,
    name: "Monkey D. Luffy",
    power: "Gomu Gomu no Mi",
    firstAppearance: "Chapter 1",
    bounty: 1500000000,
    age: 19,
  },
  {
    id: 2,
    name: "Roronoa Zoro",
    power: "Santoryu",
    firstAppearance: "Chapter 3",
    bounty: 320000000,
    age: 21,
  },
  {
    id: 3,
    name: "Nami",
    power: "Weather Manipulation",
    firstAppearance: "Chapter 8",
    bounty: 66000000,
    age: 20,
  },
  {
    id: 4,
    name: "Usopp",
    power: "Sniping",
    firstAppearance: "Chapter 23",
    bounty: 200000000,
    age: 19,
  },
  {
    id: 5,
    name: "Sanji",
    power: "Black Leg Style",
    firstAppearance: "Chapter 43",
    bounty: 330000000,
    age: 21,
  },
  {
    id: 6,
    name: "Tony Tony Chopper",
    power: "Hito Hito no Mi",
    firstAppearance: "Chapter 134",
    bounty: 100,
    age: 17,
  },
  {
    id: 7,
    name: "Nico Robin",
    power: "Hana Hana no Mi",
    firstAppearance: "Chapter 114",
    bounty: 130000000,
    age: 30,
  },
  {
    id: 8,
    name: "Franky",
    power: "Cyborg",
    firstAppearance: "Chapter 329",
    bounty: 94000000,
    age: 36,
  },
  {
    id: 9,
    name: "Brook",
    power: "Yomi Yomi no Mi",
    firstAppearance: "Chapter 442",
    bounty: 83000000,
    age: 90,
  },
  {
    id: 10,
    name: "Jinbe",
    power: "Fish-Man Karate",
    firstAppearance: "Chapter 528",
    bounty: 438000000,
    age: 46,
  },
  {
    id: 11,
    name: "Portgas D. Ace",
    power: "Mera Mera no Mi",
    firstAppearance: "Chapter 154",
    bounty: 550000000,
    age: 20,
  },
  {
    id: 12,
    name: "Shanks",
    power: "Haki",
    firstAppearance: "Chapter 1",
    bounty: 4040000000,
    age: 39,
  },
  {
    id: 13,
    name: "Dracule Mihawk",
    power: "Swordsmanship",
    firstAppearance: "Chapter 50",
    bounty: 0,
    age: 43,
  },
  {
    id: 14,
    name: "Boa Hancock",
    power: "Mero Mero no Mi",
    firstAppearance: "Chapter 516",
    bounty: 80000000,
    age: 31,
  },
  {
    id: 15,
    name: "Donquixote Doflamingo",
    power: "Ito Ito no Mi",
    firstAppearance: "Chapter 233",
    bounty: 340000000,
    age: 41,
  },
  {
    id: 16,
    name: "Crocodile",
    power: "Suna Suna no Mi",
    firstAppearance: "Chapter 126",
    bounty: 81000000,
    age: 46,
  },
  {
    id: 17,
    name: "Enel",
    power: "Goro Goro no Mi",
    firstAppearance: "Chapter 254",
    bounty: 0,
    age: 39,
  },
  {
    id: 18,
    name: "Rob Lucci",
    power: "Neko Neko no Mi, Model: Leopard",
    firstAppearance: "Chapter 323",
    bounty: 400000000,
    age: 30,
  },
  {
    id: 19,
    name: "Charlotte Katakuri",
    power: "Mochi Mochi no Mi",
    firstAppearance: "Chapter 860",
    bounty: 1057000000,
    age: 48,
  },
  {
    id: 20,
    name: "Big Mom",
    power: "Soru Soru no Mi",
    firstAppearance: "Chapter 651",
    bounty: 4388000000,
    age: 68,
  },
  {
    id: 21,
    name: "Kaido",
    power: "Uo Uo no Mi, Model: Seiryu",
    firstAppearance: "Chapter 795",
    bounty: 4611000000,
    age: 59,
  },
  {
    id: 22,
    name: "Blackbeard",
    power: "Yami Yami no Mi",
    firstAppearance: "Chapter 223",
    bounty: 2247600000,
    age: 40,
  },
  {
    id: 23,
    name: "Sabo",
    power: "Mera Mera no Mi",
    firstAppearance: "Chapter 583",
    bounty: 602000000,
    age: 22,
  },
  {
    id: 24,
    name: "Trafalgar D. Water Law",
    power: "Ope Ope no Mi",
    firstAppearance: "Chapter 498",
    bounty: 500000000,
    age: 26,
  },
  {
    id: 25,
    name: "Eustass Kid",
    power: "Magnetism",
    firstAppearance: "Chapter 498",
    bounty: 470000000,
    age: 23,
  },
  {
    id: 26,
    name: "Killer",
    power: "Combat",
    firstAppearance: "Chapter 498",
    bounty: 200000000,
    age: 25,
  },
  {
    id: 27,
    name: "X Drake",
    power: "Ryu Ryu no Mi, Model: Allosaurus",
    firstAppearance: "Chapter 498",
    bounty: 222000000,
    age: 33,
  },
  {
    id: 28,
    name: "Basil Hawkins",
    power: "Wara Wara no Mi",
    firstAppearance: "Chapter 498",
    bounty: 320000000,
    age: 31,
  },
  {
    id: 29,
    name: "Scratchmen Apoo",
    power: "Tatakau Music",
    firstAppearance: "Chapter 498",
    bounty: 350000000,
    age: 31,
  },
  {
    id: 30,
    name: "Capone Bege",
    power: "Shiro Shiro no Mi",
    firstAppearance: "Chapter 498",
    bounty: 350000000,
    age: 42,
  },
  {
    id: 31,
    name: "Urouge",
    power: "Karma",
    firstAppearance: "Chapter 498",
    bounty: 108000000,
    age: 47,
  },
  {
    id: 32,
    name: "Jewelry Bonney",
    power: "Aging",
    firstAppearance: "Chapter 498",
    bounty: 140000000,
    age: 24,
  },
  {
    id: 33,
    name: "Cavendish",
    power: "Hakuba",
    firstAppearance: "Chapter 704",
    bounty: 330000000,
    age: 26,
  },
  {
    id: 34,
    name: "Bartolomeo",
    power: "Bari Bari no Mi",
    firstAppearance: "Chapter 703",
    bounty: 200000000,
    age: 24,
  },
  {
    id: 35,
    name: "Donquixote Rosinante",
    power: "Nagi Nagi no Mi",
    firstAppearance: "Chapter 761",
    bounty: 0,
    age: 26,
  },
  {
    id: 36,
    name: "Kozuki Oden",
    power: "Swordsmanship",
    firstAppearance: "Chapter 920",
    bounty: 0,
    age: 39,
  },
  {
    id: 37,
    name: "Kin'emon",
    power: "Foxfire",
    firstAppearance: "Chapter 656",
    bounty: 0,
    age: 36,
  },
  {
    id: 38,
    name: "Kanjuro",
    power: "Fude Fude no Mi",
    firstAppearance: "Chapter 700",
    bounty: 0,
    age: 39,
  },
  {
    id: 39,
    name: "Raizo",
    power: "Ninjutsu",
    firstAppearance: "Chapter 817",
    bounty: 0,
    age: 35,
  },
  {
    id: 40,
    name: "Kikunojo",
    power: "Swordsmanship",
    firstAppearance: "Chapter 914",
    bounty: 0,
    age: 22,
  },
  {
    id: 41,
    name: "Yamato",
    power: "Oni",
    firstAppearance: "Chapter 971",
    bounty: 0,
    age: 28,
  },
];
